<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function makeTaskDone($id)
    {
        $this->em = $this->getEntityManager();
//        $query = $em
//            ->createQuery("UPDATE AppBundle:Task task SET isDone = 1 WHERE id > :taskId")
//            ->setParameter('taskId', $id);
//        $task = $query->execute();

        $qb = $this->em->createQueryBuilder();
        $q = $qb->update('AppBundle:Task', 'task')
            ->set('task.isDone', 1)
            ->where("task.id = $id")
            ->getQuery();
        $task = $q->execute();

        return $task;
    }

    public function deleteAllStuffConnectWithTask($id)
    {
        $em = $this->getEntityManager();
        $query = $em
            ->createQuery('DELETE AppBundle:Comment comment WHERE comment.task = :taskId')
            ->setParameter('taskId', $id);
        $query->execute();
    }
}
